{% set name = "csdms-ilamb" %}
{% set version = "0.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/bmi-ilamb
  git_rev: v{{ version }}

build:
  number: 0

requirements:
  build:
    - babelizer
    - ilamb
  run:
    - cca-tools
    - ilamb
    - pyyaml
    - basic-modeling-interface

test:
  requires:
    - netcdf-fortran=4.4.4=5
    - pymt==0.2

about:
  home: http://csdms.colorado.edu/wiki/Model:ILAMB
  license: MIT
  summary:
    Componentized version of the International Land Model Benchmarking
    Project (ILAMB) benchmarking toolkit.
  dev_url: https://github.com/permamodel/bmi-ilamb
